// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('change light dark mode multiple times', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('change light dark mode multiple times', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1127, 647)
    await driver.findElement(By.linkText("View Demo")).click()
    await driver.findElement(By.css(".note-menu-bar-button:nth-child(3) circle")).click()
    await driver.findElement(By.css("nav:nth-child(2) > .note-menu-bar-button:nth-child(3) > svg")).click()
    await driver.findElement(By.css(".note-menu-bar-button:nth-child(3) circle")).click()
    await driver.findElement(By.css("nav:nth-child(2) > .note-menu-bar-button:nth-child(3) > svg")).click()
    await driver.findElement(By.css(".note-menu-bar-button:nth-child(3) circle")).click()
    await driver.findElement(By.css("nav:nth-child(2) > .note-menu-bar-button:nth-child(3) > svg")).click()
  })
})
