// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('create single category', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('create single category', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1119, 639)
    await driver.findElement(By.linkText("View Demo")).click()
    await driver.findElement(By.css(".category-button > svg")).click()
    await driver.findElement(By.css(".category-form > input")).sendKeys("category 1")
    await driver.findElement(By.css(".category-form > input")).sendKeys(Key.ENTER)
    await driver.findElement(By.css("path:nth-child(3)")).click()
  })
})
