// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('create multiple notes under same category', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('create multiple notes under same category', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1116, 636)
    await driver.findElement(By.linkText("View Demo")).click()
    await driver.findElement(By.css(".category-button > svg")).click()
    await driver.findElement(By.css(".category-form > input")).sendKeys("notes2")
    await driver.findElement(By.css(".category-form > input")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".category-list-each:nth-child(2) > .category-list-name")).click()
    await driver.findElement(By.css(".action-button")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css("textarea")).sendKeys("note 1")
    await driver.findElement(By.css(".note-menu-bar-button:nth-child(2) polyline:nth-child(2)")).click()
    await driver.findElement(By.css(".action-button > span")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css("textarea")).sendKeys("note 2")
    await driver.findElement(By.css(".note-menu-bar-button:nth-child(2) polyline:nth-child(2)")).click()
  })
})
