// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('delete multiple categories', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('delete multiple categories', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1116, 636)
    await driver.findElement(By.linkText("View Demo")).click()
    await driver.findElement(By.css(".category-button > svg")).click()
    await driver.findElement(By.css(".category-form > input")).sendKeys("cat 1")
    await driver.findElement(By.css(".category-form > input")).sendKeys(Key.ENTER)
    await driver.findElement(By.css("path:nth-child(3)")).click()
    {
      const element = await driver.findElement(By.css("path:nth-child(3)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".category-button > svg")).click()
    {
      const element = await driver.findElement(By.css(".category-button > svg"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".category-form > input")).sendKeys("cat 2")
    await driver.findElement(By.css(".category-form > input")).sendKeys(Key.ENTER)
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("nav:nth-child(2) > .note-menu-bar-button:nth-child(2) > svg")).click()
    await driver.findElement(By.css(".category-list-each:nth-child(3) .context-menu-action")).click()
    await driver.findElement(By.css(".delete-option")).click()
    await driver.findElement(By.css("nav:nth-child(2) > .note-menu-bar-button:nth-child(2) > svg")).click()
    await driver.findElement(By.css(".category-list-each:nth-child(3) .context-menu-action")).click()
    await driver.findElement(By.css(".delete-option")).click()
    await driver.findElement(By.css("nav:nth-child(2) > .note-menu-bar-button:nth-child(2) > svg")).click()
  })
})
