// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('delete single category', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('delete single category', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1129, 649)
    await driver.findElement(By.linkText("View Demo")).click()
    await driver.findElement(By.css(".category-button > svg")).click()
    await driver.findElement(By.css(".category-form > input")).sendKeys("del 1")
    await driver.findElement(By.css(".category-form > input")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".category-list-each:nth-child(2) .context-menu-action")).click()
    await driver.findElement(By.css(".delete-option")).click()
    {
      const element = await driver.findElement(By.css("nav:nth-child(2) > .note-menu-bar-button:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css("nav:nth-child(2) > .note-menu-bar-button:nth-child(2) > svg"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css("nav:nth-child(2) > .note-menu-bar-button:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css("nav:nth-child(2) > .note-menu-bar-button:nth-child(2) > svg"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
  })
})
