// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('make simple synchronization', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('make simple synchronization', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1116, 636)
    await driver.findElement(By.linkText("View Demo")).click()
    await driver.findElement(By.css("nav:nth-child(2) > .note-menu-bar-button:nth-child(2) > svg")).click()
  })
})
