// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('mark single note as favorite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('mark single note as favorite', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1126, 646)
    await driver.findElement(By.linkText("View Demo")).click()
    await driver.findElement(By.css(".action-button > span")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css("textarea")).sendKeys("test note to save")
    await driver.findElement(By.css("nav:nth-child(2) > .note-menu-bar-button:nth-child(2) > svg")).click()
    await driver.findElement(By.css(".note-menu-bar-button polygon")).click()
  })
})
